[project]
name = "dinov2-3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aenum==3.1.16",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.13",
    "aiosignal==1.3.2",
    "annotated-types==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "attrs==25.3.0",
    "certifi==2025.6.15",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "debugpy==1.8.14",
    "dynamic-network-architectures",
    "einops==0.8.1",
    "filelock==3.18.0",
    "fire==0.7.0",
    "frozenlist==1.7.0",
    "fsspec==2025.5.1",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "hf-xet==1.1.5",
    "huggingface-hub==0.33.4",
    "hydra-core==1.3.2",
    "idna==3.10",
    "importlib-resources==6.5.2",
    "itk==5.4.4.post1",
    "itk-core==5.4.4.post1",
    "itk-filtering==5.4.4.post1",
    "itk-io==5.4.4.post1",
    "itk-numerics==5.4.4.post1",
    "itk-registration==5.4.4.post1",
    "itk-segmentation==5.4.4.post1",
    "jinja2==3.1.6",
    "lightly==1.5.21",
    "lightly-utils==0.0.2",
    "lightning-utilities==0.14.3",
    "markupsafe==3.0.2",
    "monai==1.4.0",
    "mpmath==1.3.0",
    "multidict==6.6.3",
    "networkx==3.5",
    "nibabel==5.3.2",
    "numpy==1.26.4",
    "nvidia-cublas-cu12==12.6.4.1",
    "nvidia-cuda-cupti-cu12==12.6.80",
    "nvidia-cuda-nvrtc-cu12==12.6.77",
    "nvidia-cuda-runtime-cu12==12.6.77",
    "nvidia-cudnn-cu12==9.5.1.17",
    "nvidia-cufft-cu12==11.3.0.4",
    "nvidia-cufile-cu12==1.11.1.6",
    "nvidia-curand-cu12==10.3.7.77",
    "nvidia-cusolver-cu12==11.7.1.2",
    "nvidia-cusparse-cu12==12.5.4.2",
    "nvidia-cusparselt-cu12==0.6.3",
    "nvidia-nccl-cu12==2.26.2",
    "nvidia-nvjitlink-cu12==12.6.85",
    "nvidia-nvtx-cu12==12.6.77",
    "omegaconf==2.3.0",
    "packaging==25.0",
    "pillow==11.3.0",
    "platformdirs==4.3.8",
    "propcache==0.3.2",
    "protobuf==6.31.1",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "python-dateutil==2.9.0.post0",
    "pytorch-lightning==2.5.2",
    "pyyaml==6.0.2",
    "requests==2.32.4",
    "safetensors==0.5.3",
    "sentry-sdk==2.32.0",
    "setuptools==80.9.0",
    "six==1.17.0",
    "smmap==5.0.2",
    "sympy==1.14.0",
    "termcolor==3.1.0",
    "timm==1.0.17",
    "torch==2.7.1",
    "torchmetrics==1.7.3",
    "torchvision==0.22.1",
    "tqdm==4.67.1",
    "triton==3.3.1",
    "typing-extensions==4.14.0",
    "typing-inspection==0.4.1",
    "urllib3==2.5.0",
    "wandb==0.21.0",
    "yarl==1.20.1",
]

[tool.uv.sources]
dynamic-network-architectures = { git = "https://github.com/MIC-DKFZ/dynamic-network-architectures.git", rev = "6d9f47ebc53dfbc679c6c68a93f4f92d34cb3766" }
